feat: prompt user wallet when paying an invoice
GaloyMoney/galoy-pay pull request #432
Opened 2023-03-22 20:11 UTC by IgboPharaoh

The pr introduces a feature for #333 to enable users to select their wallet of choice when paying an invoice. 
- After a user has created an invoice there is a **pay with wallet** button which works in two ways;
   1 -  For mobile devices the user is routed to the play store or app store to download the bitcoin beach wallet or open it from there if already installed. Deep linking to the bitcoin beach wallet and immediately opening it was not possible because you cannot directly access the path to an already installed application because PWAs are installed as web applications rather than native applications which have the ability to use [intents](https://developer.android.com/guide/components/intents-filters#kotlin). 

   2 - For desktop devices, a modal pops up which shows the user the possible wallet options you can use to pay the invoice. You can easily use the bitcoin beach wallet to do this.

![image](https://user-images.githubusercontent.com/87058633/227044493-1c8bd777-d8b0-4868-9967-4456aa76dc99.png)

2023-03-22 22:55 UTC, nicolasburtey commented
didn't skimmed through the PR, but looking at the visual you provide, this looks good. maybe you can add the logo of BBW?

2023-03-23 06:43 UTC, IgboPharaoh commented
Alright, that will be done

2023-03-23 08:09 UTC, Extheoisah requested changes
This looks good! Just some comments.
Please change the PR title to follow conventional commits https://www.conventionalcommits.org/en/v1.0.0/

2023-03-23 08:09 UTC, Extheoisah commented on components/ParsePOSPayment/Receive-Invoice.tsx
> +            You can payment with
This should be
```suggestion
            You can make payment with
```
or 
```
You can pay with
```

2023-03-23 08:12 UTC, Extheoisah requested changes

2023-03-23 08:12 UTC, Extheoisah commented on components/ParsePOSPayment/Receive-Invoice.tsx
> +                src="/manifest-logo/logo144x144.svg"
Please use the bbw app logo here. this is the cash register's logo
```suggestion
                src="/manifest-logo/logo144x144.svg"
```

2023-03-23 09:59 UTC, IgboPharaoh commented
> didn't skimmed through the PR, but looking at the visual you provide, this looks good. maybe you can add the logo of BBW?



> This looks good! Just some comments. Please change the PR title to follow conventional commits https://www.conventionalcommits.org/en/v1.0.0/

![image](https://user-images.githubusercontent.com/87058633/227168209-7389aa2b-5975-4499-af2f-5caaa4f5c336.png)

2023-03-27 15:01 UTC, Extheoisah approved these changes
looks good. nice work

2023-03-27 15:04 UTC, merged